### ISSUE TITLE
Cast

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/tipi_avanzati#1]
Togli il void tra le parentesi del main (è pratica vecchia)

Attenzione al gitignore

**Comment by Giandomenico-bit** [comment]
strano.. il mio riporta  libro fra le parentesi di qualsiasi funzione, main incluso, la parola chiave void per indicare che non viene passato nessun parametro.

**Comment by FabioZTessitore** [comment]
Versione molto vecchia del C, prima addirittura dello standard

**Comment by Giandomenico-bit** [comment]
ah capisco? per questo nel codice sorgente della funzione printf c'è ancora la parola chiave void come parametri della funzione

**Comment by Giandomenico-bit** [comment]
!*

**Comment by FabioZTessitore** [comment]
Dove l'hai vista questa cosa su printf?

Il mer 27 nov 2019, 01:00 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
nella libreria standard del C. Ho visto parecchie funzioni che riportano ancora la parola chiave void per indicare che non viene passato nessun parametro.

**Comment by FabioZTessitore** [comment]
Ma non printf

Il mer 27 nov 2019, 20:14 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
ah allora ho sbagliato a vedere

**Comment by FabioZTessitore** [comment]
Prende almeno una stringa

Il mer 27 nov 2019, 20:33 Giandomenico-bit <notifications@github.com> ha
scritto:

**Comment by Giandomenico-bit** [comment]
si infatti però se non ricordo male vidi dei prototipi di funzione all'interno del file dove stava definita la funzione printf, e questi avevano come parametro formale void
