### ISSUE TITLE
Asterischi 

### ISSUE THREAD

**Issue by FabioZTessitore** [Giandomenico-bit/tipi_avanzati#2]
Non ci siamo. Il programma deve attendere tra una stampa e l'altra

**Comment by Giandomenico-bit** [comment]
ho capito

**Comment by FabioZTessitore** [comment]
Guarda che il tuo programma non attende il tempo prestabilito

**Comment by Giandomenico-bit** [comment]
oddio che sbadato! non mi sono accorto di non aver messo la funzione nanosleep
